version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  kibana:
    image: kibana:7.9.2
    ports:
      - '5601:5601'
    networks:
      - elastic
  redis01:
    image: redis:latest
    container_name: redis01
    ports:
      - 6379:6379
    networks:
      - redis
networks:
  elastic:
    driver: bridge
  redis:
    driver: bridge