version: "3"
services:
  redis01:
    image: redis:latest
    container_name: redis01
    ports:
      - 6379:6379
    networks:
      - redis
  elasticsearch01:
    image: elasticsearch:8.0.0
    container_name: elasticsearch01
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    networks:
      - elastic

  kibana01:
    image: kibana:8.0.0
    container_name: kibana01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch01:9200
      MEM_LIMIT: 4073741824
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
  redis:
    driver: bridge